### ISSUE TITLE
Python does not work with harness

### ISSUE THREAD

**Issue by Tjorriemorrie** [EntelectChallenge/2015-SpaceInvaders-Bot-Python#1]
Running the very [basic script](https://gist.github.com/Tjorriemorrie/08289c2a82a422c1500f) the bot.log always give:

```
/c: /c: is a directory
[GAME]  Bot Tjorriemorrie finished in 29 ms.
[GAME]  Process exited with non-zero code 126 from player Tjorriemorrie.
[GAME]  No output file from player Tjorriemorrie
```

when running SpaceInvadersDuel.exe

**Comment by Tjorriemorrie** [comment]
Running 

> run.bat output

results in no error; the move.txt file is created properly

**Comment by mattpwest** [comment]
I just tested with the 1.0.0 binary release:
- I removed the contents of player2/
- I copied our sample Python bot into player2/
- I replaced our main.py with your [basic script](https://gist.github.com/Tjorriemorrie/08289c2a82a422c1500f).
- I then ran SpaceInvadersDuel.exe from the command line.

It worked fine for me... Maybe try the 1.0.1 release which will be up shortly.

If still not resolved please give me more information:
- What O/S version are you running?
- Python version?
- .NET framework version installed?
- Standard Command Prompt or Git Bash?

**Comment by Tjorriemorrie** [comment]
I'll close this issue and continue with the issue on the TestHarness. Just running the default players in 1.0.1 still gives me the problems.
